export const auctions = [
    { name: "Rolex Submariner", price: 11000, open: true },
    { name: "Omega Speedmaster Professional", price: 7200, open: true },
    { name: "Audemars Piguet Royal Oak", price: 38000, open: false },
    { name: "Patek Philippe Nautilus", price: 55000, open: true },
    { name: "Tag Heuer Carrera", price: 4500, open: true },
    { name: "Breitling Navitimer", price: 7600, open: true },
    { name: "IWC Portugieser", price: 9100, open: false },
    { name: "Jaeger-LeCoultre Reverso", price: 9200, open: true },
    { name: "Cartier Santos", price: 6900, open: true },
    { name: "Panerai Luminor", price: 8000, open: true },
    { name: "Vacheron Constantin Overseas", price: 43000, open: true },
    { name: "Hublot Big Bang", price: 14000, open: true },
    { name: "Zenith El Primero", price: 7800, open: true },
    { name: "Blancpain Fifty Fathoms", price: 15000, open: true },
    { name: "Richard Mille RM 11-03", price: 215000, open: false },
    { name: "Ulysse Nardin Freak", price: 26000, open: true },
    { name: "Breguet Classique", price: 20000, open: true },
    { name: "A. Lange & Söhne Lange 1", price: 47000, open: true },
    { name: "Glashütte Original Senator", price: 9300, open: true },
    { name: "Grand Seiko Spring Drive", price: 7200, open: true },
    { name: "Rolex Daytona", price: 14000, open: false },
    { name: "Omega Seamaster Diver 300M", price: 5300, open: true },
    { name: "Tag Heuer Monaco", price: 6900, open: true },
    { name: "Breitling Superocean", price: 5000, open: true },
    { name: "IWC Big Pilot", price: 12900, open: true },
    { name: "Cartier Ballon Bleu", price: 6500, open: true },
    { name: "Panerai Radiomir", price: 7500, open: true },
    { name: "Jaeger-LeCoultre Master Ultra Thin", price: 8900, open: true },
    { name: "Hublot Classic Fusion", price: 9800, open: true },
    { name: "Audemars Piguet Code 11.59", price: 30000, open: true },
    { name: "Patek Philippe Calatrava", price: 29000, open: true },
    { name: "Zenith Defy", price: 8700, open: true },
    { name: "Vacheron Constantin Patrimony", price: 35000, open: true },
    { name: "Breguet Marine", price: 23000, open: true },
    { name: "Richard Mille RM 07-01", price: 160000, open: true },
    { name: "Blancpain Villeret", price: 12000, open: true },
    { name: "Grand Seiko Snowflake", price: 6400, open: true },
    { name: "Ulysse Nardin Marine", price: 9700, open: true },
    { name: "A. Lange & Söhne Saxonia", price: 31000, open: true },
    { name: "Glashütte Original PanoMaticLunar", price: 10500, open: true },
    { name: "Rolex GMT-Master II", price: 13500, open: true },
    { name: "Omega Constellation", price: 5900, open: true },
    { name: "Tag Heuer Aquaracer", price: 3200, open: true },
    { name: "Breitling Avenger", price: 7100, open: true },
    { name: "IWC Ingenieur", price: 8800, open: true },
    { name: "Cartier Tank Française", price: 5600, open: true },
    { name: "Panerai Submersible", price: 9000, open: true },
    { name: "Jaeger-LeCoultre Polaris", price: 8700, open: true },
    { name: "Zenith Pilot Type 20", price: 6900, open: true }
  ];
  